//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccomerceWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaliMaliDbEntities : DbContext
    {
        public MaliMaliDbEntities()
            : base("name=MaliMaliDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer_Reg_Table> Customer_Reg_Table { get; set; }
        public virtual DbSet<Fcm_Token_Table> Fcm_Token_Table { get; set; }
        public virtual DbSet<Products_Table> Products_Table { get; set; }
    }
}
