//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccomerceWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Table
    {
        public int Product_ID { get; set; }
        public string Product_Image { get; set; }
        public string Product_Name { get; set; }
        public string Product_Desc { get; set; }
        public string Product_Price { get; set; }
    }
}
